/**:
  ros__parameters:
    distance_from_wall: 0.55
    distance_to_stop: 0.3
    max_linear_vel: 0.22
    max_angular_vel: 2.84
    min_angular_vel: -2.84
    sampling_rate: 0.033
    kp: 1.2
    ki: 0.0
    kd: 0.0